# Generated by Django 5.1 on 2024-09-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=500)),
                ('estados', models.CharField(choices=[('completo', 'Finalizado'), ('incompleto', 'pendiente')], default='incompleto', max_length=20)),
            ],
        ),
    ]
